# Generated by Django 4.0.4 on 2022-11-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userProfileImage',
            new_name='user_image',
        ),
    ]
