# Generated by Django 4.0.4 on 2022-11-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_userprofileimage_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
