# Generated by Django 4.0.4 on 2022-12-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='network.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
