# Generated by Django 4.0.4 on 2022-12-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_post_parent_alter_post_post_date_delete_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_parent',
        ),
        migrations.AddField(
            model_name='post',
            name='post_replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostHasReplies', to='network.post'),
        ),
    ]
