# Generated by Django 4.0.4 on 2022-12-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_post_parent_post_post_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_replies',
            new_name='post_reply',
        ),
    ]
