# Generated by Django 4.0.4 on 2022-12-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
